spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot