create table article
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    primary key(id)
);

CREATE TABLE users (
    id bigint generated by default as identity,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint NOT NULL,
    refresh_token VARCHAR(255) NOT NULL
);