create table article
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    primary key(id)
);

CREATE TABLE users (
    id bigint generated by default as identity,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
